version: "3.10"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "psql://postgres:postgres@db:5432/postgres"
      DJANGO_SETTINGS_MODULE: drf_test.settings.local
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  db:
    image: postgres
    volumes:
      - shared_database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
volumes:
  shared_database: